<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Analytics - Cyclevent</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800&display=swap');
        
        @page { size: A4 portrait; margin: 15mm; }
        
        body {
            font-family: 'Montserrat', sans-serif;
            color: #111;
            margin: 0; padding: 0;
            background: #fff;
            position: relative;
        }

        /* Watermark Background */
        .watermark {
            position: fixed;
            top: 50%; left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 6rem;
            color: rgba(0, 0, 0, 0.03);
            font-weight: 800;
            text-transform: uppercase;
            white-space: nowrap;
            z-index: -1;
            user-select: none;
            pointer-events: none;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }

        .header h1 { margin: 0; font-size: 1.5rem; font-weight: 800; text-transform: uppercase; }
        .header p { margin: 5px 0 0; font-size: 0.875rem; color: #555; }

        .info-box {
            margin-bottom: 20px;
            font-size: 0.875rem;
        }
        .info-box strong { display: inline-block; width: 120px; }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
            font-size: 0.85rem;
        }
        
        th, td {
            border: 1px solid #ccc;
            padding: 8px 12px;
            text-align: center;
        }
        
        th {
            background: #f4f4f4;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.05em;
        }

        td.date-col { text-align: left; font-weight: 600; }

        tr:nth-child(even) { background: #fafafa; }
        tr.total-row { background: #e8e8e8; font-weight: 800; }
        
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 0.75rem;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }

        @media print {
            .no-print { display: none !important; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
        
        .print-btn {
            display: block;
            width: 200px;
            margin: 20px auto;
            padding: 12px 20px;
            background: var(--yellow);
            color: #000;
            text-align: center;
            font-weight: 700;
            text-transform: uppercase;
            text-decoration: none;
            border-radius: 4px;
            cursor: pointer;
            border: 1px solid #000;
        }
    </style>
</head>
<body onload="window.print()">

<div class="watermark">generated system hvmdigital.id</div>

<a href="#" class="print-btn no-print" onclick="window.print(); return false;">🖨️ Cetak / Simpan PDF</a>

<div class="header">
    <h1>Laporan Analytics Website</h1>
    <p>Cyclevent</p>
</div>

<div class="info-box">
    <div><strong>Periode Laporan</strong> : {{ $from->format('d/m/Y') }} s/d {{ $to->format('d/m/Y') }}</div>
    <div><strong>Tanggal Cetak</strong> : {{ now()->format('d/m/Y H:i') }}</div>
    <div><strong>Generated By</strong> : System hvmdigital.id</div>
</div>

<table>
    <thead>
        <tr>
            <th>Tanggal</th>
            <th>Bulan</th>
            <th>Tahun</th>
            <th>Visitor</th>
            <th>Klik WA</th>
            <th>Leads</th>
            <th>CTR</th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $row)
        <tr>
            <td class="date-col">{{ $row['tgl'] }}</td>
            <td>{{ $row['bln'] }}</td>
            <td>{{ $row['thn'] }}</td>
            <td>{{ number_format($row['v']) }}</td>
            <td>{{ number_format($row['w']) }}</td>
            <td>{{ number_format($row['l']) }}</td>
            <td>{{ $row['c'] }}%</td>
        </tr>
        @endforeach
        <tr class="total-row">
            <td colspan="3" style="text-align:right; padding-right:15px;">TOTAL KESELURUHAN</td>
            <td>{{ number_format($totals['v']) }}</td>
            <td>{{ number_format($totals['w']) }}</td>
            <td>{{ number_format($totals['l']) }}</td>
            <td>{{ $totals['c'] }}%</td>
        </tr>
    </tbody>
</table>

<div class="footer">
    Dokumen ini digenerate secara otomatis oleh sistem hvmdigital.id pada {{ now()->format('d F Y') }}.
</div>

</body>
</html>
