<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Leads - Cyclevent</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800&display=swap');
        @page { size: A4 landscape; margin: 12mm; }

        body {
            font-family: 'Montserrat', Arial, sans-serif;
            color: #111;
            margin: 0; padding: 0;
            background: #fff;
        }

        .watermark {
            position: fixed;
            top: 50%; left: 50%;
            transform: translate(-50%, -50%) rotate(-30deg);
            font-size: 4.5rem;
            color: rgba(0,0,0,0.03);
            font-weight: 800;
            text-transform: uppercase;
            white-space: nowrap;
            z-index: -1;
            pointer-events: none;
        }

        .header {
            border-bottom: 3px solid #000;
            padding-bottom: 12px;
            margin-bottom: 18px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        .header h1 { margin: 0; font-size: 1.25rem; font-weight: 800; text-transform: uppercase; letter-spacing: -0.02em; }
        .header p { margin: 3px 0 0; font-size: 0.75rem; color: #555; }
        .header-right { text-align: right; font-size: 0.75rem; color: #555; line-height: 1.6; }

        .info-row {
            display: flex; gap: 30px; margin-bottom: 18px;
            background: #f8f8f8; padding: 10px 16px; border-left: 4px solid var(--yellow);
            font-size: 0.8rem;
        }
        .info-row div { display: flex; gap: 6px; }
        .info-row strong { color: #111; }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.7rem;
            margin-bottom: 20px;
        }

        th {
            background: #111;
            color: var(--yellow);
            padding: 7px 10px;
            text-align: left;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 0.6rem;
            letter-spacing: 0.07em;
            white-space: nowrap;
        }

        td {
            border: 1px solid #e0e0e0;
            padding: 6px 10px;
            vertical-align: top;
            line-height: 1.4;
        }

        tr:nth-child(even) td { background: #fafafa; }
        tr:hover td { background: #fff8e0; }

        .status-badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 100px;
            font-size: 0.6rem;
            font-weight: 700;
            text-transform: uppercase;
        }
        .status-new { background: #fef9c3; color: #854d0e; border: 1px solid #fde047; }
        .status-contacted { background: #dbeafe; color: #1e40af; border: 1px solid #93c5fd; }
        .status-closed { background: #dcfce7; color: #166534; border: 1px solid #86efac; }

        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 0.65rem;
            color: #888;
            border-top: 1px solid #eee;
            padding-top: 8px;
        }
        .total-row {
            font-weight: 800;
            background: #f0f0f0 !important;
        }

        @media print {
            .no-print { display: none !important; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }

        .print-btn {
            display: block; width: 220px;
            margin: 16px auto;
            padding: 10px 20px;
            background: var(--yellow); color: #000;
            text-align: center; font-weight: 700;
            text-transform: uppercase;
            text-decoration: none;
            border-radius: 4px; cursor: pointer;
            border: 1px solid #000; font-family: inherit;
            font-size: 0.875rem;
        }
    </style>
</head>
<body onload="window.print()">

<div class="watermark">generated system hvmdigital.id</div>

<button class="print-btn no-print" onclick="window.print()">🖨️ Cetak / Simpan PDF</button>

<div class="header">
    <div>
        <h1>Laporan Data Leads</h1>
        <p>Cyclevent &mdash; produsenhoistcranelift.com</p>
    </div>
    <div class="header-right">
        <div>Generated by System hvmdigital.id</div>
        <div>{{ now()->format('d F Y, H:i') }}</div>
    </div>
</div>

<div class="info-row">
    <div><strong>Periode:</strong> <span>{{ $from->format('d/m/Y') }} &mdash; {{ $to->format('d/m/Y') }}</span></div>
    <div><strong>Total Leads:</strong> <span>{{ $leads->count() }}</span></div>
    <div><strong>Status Baru:</strong> <span>{{ $leads->where('status','new')->count() }}</span></div>
    <div><strong>Diproses:</strong> <span>{{ $leads->where('status','contacted')->count() }}</span></div>
    <div><strong>Selesai:</strong> <span>{{ $leads->where('status','closed')->count() }}</span></div>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Tanggal</th>
            <th>Bulan</th>
            <th>Tahun</th>
            <th>Waktu</th>
            <th>Nama</th>
            <th>Perusahaan</th>
            <th>Email</th>
            <th>Telepon</th>
            <th>Produk</th>
            <th>Sumber</th>
            <th>Perangkat</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($leads as $i => $lead)
        <tr>
            <td style="color:#aaa; text-align:center;">{{ $i + 1 }}</td>
            <td style="text-align:center; font-weight:700;">{{ $lead->created_at->format('d') }}</td>
            <td style="white-space:nowrap;">{{ $lead->created_at->format('M') }}</td>
            <td>{{ $lead->created_at->format('Y') }}</td>
            <td style="white-space:nowrap; color:#555;">{{ $lead->created_at->format('H:i') }}</td>
            <td style="font-weight:700; color:#111;">{{ $lead->name }}</td>
            <td style="color:#555;">{{ $lead->company ?: '-' }}</td>
            <td style="color:#3B82F6;">{{ $lead->email ?: '-' }}</td>
            <td style="white-space:nowrap; font-weight:600;">{{ $lead->phone }}</td>
            <td style="color:#555; max-width:120px;">{{ $lead->product ?: '-' }}</td>
            <td style="font-size:0.6rem;">{{ $lead->source ?: 'Website' }}</td>
            <td style="font-size:0.6rem; white-space:nowrap;">{{ $lead->device_type ?: '-' }}</td>
            <td>
                @if($lead->status === 'new')
                    <span class="status-badge status-new">Baru</span>
                @elseif($lead->status === 'contacted')
                    <span class="status-badge status-contacted">Diproses</span>
                @else
                    <span class="status-badge status-closed">Selesai</span>
                @endif
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="13" style="text-align:center; padding:2rem; color:#aaa;">Tidak ada data untuk periode ini.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Dokumen ini digenerate secara otomatis oleh sistem hvmdigital.id &mdash; Dicetak pada {{ now()->format('d F Y H:i') }}
</div>

</body>
</html>
