<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Lead;
use Illuminate\Http\Request;

class AdminLeadController extends Controller
{
    public function index()
    {
        $leads = Lead::latest()->paginate(25);
        $stats = [
            'total'      => Lead::count(),
            'today'      => Lead::today()->count(),
            'this_month' => Lead::thisMonth()->count(),
            'new'        => Lead::new()->count(),
        ];
        return view('admin.leads.index', compact('leads', 'stats'));
    }

    public function show(Lead $lead)
    {
        return view('admin.leads.show', compact('lead'));
    }

    public function updateStatus(Request $request, Lead $lead)
    {
        $request->validate(['status' => 'required|in:new,contacted,closed']);
        $lead->update(['status' => $request->status]);
        return back()->with('success', 'Status lead diperbarui.');
    }

    public function markAllRead()
    {
        Lead::where('status', 'new')->update(['status' => 'contacted']);
        return back()->with('success', 'Semua notifikasi baru telah ditandai sebagai dibaca.');
    }

    public function updateNote(Request $request, Lead $lead)
    {
        $request->validate(['notes' => 'nullable|max:2000']);
        $lead->update(['notes' => $request->notes]);
        return back()->with('success', 'Catatan disimpan.');
    }

    public function destroy(Lead $lead)
    {
        $lead->delete();
        return back()->with('success', 'Lead dihapus.');
    }

    public function export(Request $request)
    {
        if (!$request->filled('start_date') || !$request->filled('end_date')) {
            return back()->with('error', 'Silakan pilih periode tanggal terlebih dahulu sebelum download laporan.');
        }

        $query = Lead::latest();
        $query->whereDate('created_at', '>=', $request->start_date);
        $query->whereDate('created_at', '<=', $request->end_date);
        $leads = $query->get();

        $filename = 'leads-cyclevent-' . $request->start_date . '_' . $request->end_date . '.csv';

        $headers = [
            'Content-Type'        => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ];

        $callback = function () use ($leads) {
            $handle = fopen('php://output', 'w');
            fwrite($handle, "\xEF\xBB\xBF"); // BOM for Excel

            // Watermark / info rows
            fputcsv($handle, ['Generated By:', 'System hvmdigital.id']);
            fputcsv($handle, ['Tanggal Cetak:', now()->format('d/m/Y H:i')]);
            fputcsv($handle, []);

            // Header row
            fputcsv($handle, [
                'Tanggal', 'Bulan', 'Tahun', 'Waktu',
                'Nama', 'Perusahaan', 'Email', 'Telepon/WA',
                'Produk', 'Sumber', 'Perangkat',
                'Status', 'Pesan/Kebutuhan',
            ]);

            foreach ($leads as $lead) {
                fputcsv($handle, [
                    $lead->created_at->format('d'),
                    $lead->created_at->format('F'),
                    $lead->created_at->format('Y'),
                    $lead->created_at->format('H:i'),
                    $lead->name,
                    $lead->company ?? '',
                    $lead->email ?? '',
                    $lead->phone,
                    $lead->product ?? '',
                    $lead->source ?? 'Website',
                    $lead->device_type ?? '',
                    $lead->status_label,
                    $lead->message ?? '',
                ]);
            }

            fclose($handle);
        };

        return response()->stream($callback, 200, $headers);
    }

    public function exportPdf(Request $request)
    {
        if (!$request->filled('start_date') || !$request->filled('end_date')) {
            return back()->with('error', 'Silakan pilih periode tanggal terlebih dahulu sebelum download PDF.');
        }

        $query = Lead::latest();
        $query->whereDate('created_at', '>=', $request->start_date);
        $query->whereDate('created_at', '<=', $request->end_date);
        $leads = $query->get();

        $from = \Carbon\Carbon::parse($request->start_date);
        $to   = \Carbon\Carbon::parse($request->end_date);

        return view('admin.exports.leads_pdf', compact('leads', 'from', 'to'));
    }
}
